### ISSUE TITLE
[question ] compiling against 5.1.0 M2

### ISSUE THREAD

**Issue by hnoble64** [colinsheppard/time#29]
Hello again,
I'd like to try to compile the time extension to work with the latest release of NetLogo (5.1.0 M2) ... because I would like to use the Model Runs extension too.

I think I should do this by following the instructions here: https://github.com/colinsheppard/time/#building but there's no NetLogoLite.jar in this release as far as I can see. Can you give me some instructions on how to try to compile the latest time code for M2?

Sorry to bother you again!

Howard

**Comment by colinsheppard** [comment]
The time extension is now compatible with NetLogo 6.0:

[https://github.com/colinsheppard/time/releases/tag/v1.4.0](https://github.com/colinsheppard/time/releases/tag/v1.4.0)
