### ISSUE TITLE
How to cite the time extension?

### ISSUE THREAD

**Issue by annaklabunde** [colinsheppard/time#42]
Hi Colin,

we would like to cite your extension in a paper; which is the best way to do this? 
Thanks a lot in advance and best wishes

Anna

**Comment by colinsheppard** [comment]
Hi Anna, thanks for the credit. You could cite like this:

Sheppard, Colin J.R. and Steve Railsback (2015). Time Extension for NetLogo. (Version 1.2) [Software]. Available from https://github.com/colinsheppard/time.
