### ISSUE TITLE
time:go creates NullPointerException error

### ISSUE THREAD

**Issue by MHX792** [colinsheppard/time#43]
My code:
```NetLogo
extensions [
  time
]

to setup
  ca
  create-turtles 5
  time:schedule-event turtles (task fd) 10
  time:schedule-event (turtle 1) (task fd) 5
end
```

The error that appears both in NetLogo 5.0.4 and 5.2:
```NetLogo
error (NullPointerException)
 while observer running TIME:GO
  called by procedure GO
  called by Button 'go'

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.NullPointerException
 at TimeExtension$LogoSchedule.performScheduledTasks(TimeExtension.java:593)
 at TimeExtension$LogoSchedule.performScheduledTasks(TimeExtension.java:578)
 at TimeExtension$Go.perform(TimeExtension.java:1655)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0.4
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-466.1-11M4716)
operating system: Mac OS X 10.10.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: DES test 5.0.4

04:14:41.545 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
04:14:41.542 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:14:41.542 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:14:41.542 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
04:14:41.399 InputBoxLoseFocusEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
04:14:41.374 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:14:41.174 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:14:40.973 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:14:40.745 JobRemovedEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
04:14:40.701 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

**Comment by SethTisue** [comment]
also reported at http://stackoverflow.com/questions/33118707/timego-creates-nullpointerexception-error-in-netlogo

**Comment by colinsheppard** [comment]
There was a bug here which I fixed, but your code is also not appropriate for how the extension is designed. All tasks have to be command tasks (which can't have any arguments), so to do something like execute fd, you have to wrap it up in a procedure like this:

extensions [
  time
]

to setup
  create-turtles 5
  time:schedule-event turtles (task go-forward) 10
  time:schedule-event (turtle 1) (task go-forward) 5
  time:go
end

to go-forward
  fd 2
end

**Comment by SethTisue** [comment]
or just `task [ fd 2 ]`, it isn't necessary to put the task body in a procedure, I wouldn't think?

**Comment by SethTisue** [comment]
also, couldn't the extension notice when it's given a task that expects input, and immediately raise an error?

**Comment by colinsheppard** [comment]
Hi Seth, I do have a check to ensure the task is an `instanceof CommandTask`, but apparently when `(task fd 1)` is used, it passes this check instead of fails. Can you advise on how to determine if a task is expecting arguments?

**Comment by SethTisue** [comment]
unfortunately https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/api/Task.scala doesn't have offer a method for that — I imagine a patch adding one would be accepted.

but you can work around it by casting to `org.nlogo.nvm.Task` ([source](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/nvm/Task.scala)) then calling `.formals.size` (Scala) or `.formals().size()` (Java)

**Comment by colinsheppard** [comment]
Thanks Seth, got that to work.

**Comment by SethTisue** [comment]
Awesome! But the terminology in the error message (and, I now see, the previous discussion on this ticket) isn't quite right. `task [ fd 5 ]` and `task [ fd ? ]` are both command tasks. The former is a command task that takes zero inputs, the latter is a command task that takes one input. (_Every_ task is either a command task or a reporter task; this is completely orthogonal to whether the tasks takes inputs.)

**Comment by colinsheppard** [comment]
Sheesh.... thanks for setting me straight. Now it's hopefully more clear.
