### ISSUE TITLE
running time extension on netlogo 6.0

### ISSUE THREAD

**Issue by craig-tony** [colinsheppard/time#51]
I was wondering if there was any possibility of running the time extension on the new version of netlogo?  I can't seem to get it to work.

**Comment by colinsheppard** [comment]
Thanks for the reminder. I've updated the extension to work with Netlogo 6.0.  See:
 
[https://github.com/colinsheppard/time/releases/tag/v1.4.0](https://github.com/colinsheppard/time/releases/tag/v1.4.0)
