### ISSUE TITLE
Leap years

### ISSUE THREAD

**Issue by MARIASUAM** [colinsheppard/time#54]
Hi @colinsheppard,
How could I make NetLogo identify if the year the simulation is at a tick is a leap year or not?

Thanks,

María

**Comment by SFRailsback** [comment]
Hi Colin, I cannot close this issue but I talked to Maria about this and you can safely close it.

Steve

**Comment by MARIASUAM** [comment]
Hi,

Yes, you can close it safely.

Thanks!

**Comment by colinsheppard** [comment]
Ok, thanks. Sorry I didn't notice this back in April when you first created it.
